# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0800dfc3c7fdd80f6dc75619132de09cf80552aa0777bdecc0de77f9f5bd7eaaa8d67bbf58b95eb3d36312193583ef9fad8342b123cfd71176315891ad885d51

test:
  secret_key_base: 8ab52961b3c8e6dd029191b62aee2fdb99f5943df38d62246dc0d3fff76097d438733fdf95be4b9deb278ff492d324060cf4b4776177374cb5533e7575f5e5bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
